update

diff --git a/diy/luci-app-ssr-plus/root/etc/init.d/shadowsocksr b/diy/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
--- a/diy/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
+++ b/diy/luci-app-ssr-plus/root/etc/init.d/shadowsocksr
@@ -54,9 +54,9 @@ dns_mode_l=$(uci_get_by_type global dns_mode_l 0)
 firstdown(){
 	[ $1 = 1 ] && A=$BIN_DIR/checknetwork && B=check
 	[ $1 = 2 ] && A=$BIN_DIR/update && B=--First
-	retry=1
+	r=1
 	while ps -w | grep $A | grep -v grep >/dev/null 2>&1;do
-		[ $retry -ge 10 ] && return 1 || let retry++
+		[ $r -ge 10 ] && return 1 || let r++
 		sleep 1
 	done
 	rm -f /var/lock/ssr-plus.lock
@@ -201,9 +201,9 @@ start_rules(){
 	server=$(uci_get_by_name $GLOBAL_SERVER server)
 	if ! echo $server | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 		if [ -f /var/lock/ssr-plusboot.lock ];then
-			retry=1
+			r=1
 			while ! nslookup $server >/dev/null 2>&1;do
-				[ $retry -ge 20 ] && return 1 || let retry++
+				[ $r -ge 20 ] && return 1 || let r++
 				sleep 1
 			done
 		fi
@@ -225,9 +225,9 @@ start_rules(){
 		udp_server=$(uci_get_by_name $UDP_RELAY_SERVER server)
 		if ! echo $udp_server | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 			if [ -f /var/lock/ssr-plusboot.lock ];then
-				retry=1
+				r=1
 				while ! nslookup $udp_server >/dev/null 2>&1;do
-					[ $retry -ge 20 ] && return 1 || let retry++
+					[ $r -ge 20 ] && return 1 || let r++
 					sleep 1
 				done
 			fi
@@ -252,9 +252,9 @@ start_rules(){
 		nf_ip=$(uci_get_by_name $NF_SERVER server)
 		if ! echo $nf_ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 			if [ -f /var/lock/ssr-plusboot.lock ];then
-				retry=1
+				r=1
 				while ! nslookup $nf_ip >/dev/null 2>&1;do
-					[ $retry -ge 20 ] && return 1 || let retry++
+					[ $r -ge 20 ] && return 1 || let r++
 					sleep 1
 				done
 			fi
@@ -281,13 +281,13 @@ start_rules(){
 	fi
 
 	[ -s $LOG -a $LOG_S = 0 ] && eval $LOG_B
-	if $BIN_DIR/ssr-rules -s "$server" -l "$local_port" -a "$ac_ips" -b "$(uci_get_by_type access_control wan_bp_ips)" -w "$(uci_get_by_type access_control wan_fw_ips)" \
-		-p "$(uci_get_by_type access_control lan_fp_ips)" -G "$(uci_get_by_type access_control lan_gm_ips)" -D "$proxyport" $mode $UDP $NF;then
-		echo "`eval $DATE` SSR-rules : Start iptables rules successful!" >> $LOG
-	else
-		echo "`eval $DATE` SSR-rules : Start iptables rules failed!" >> $LOG
-		$BIN_DIR/ssr-rules -f;return 1
-	fi
+	r=1
+	while ! $BIN_DIR/ssr-rules -s "$server" -l "$local_port" -a "$ac_ips" -b "$(uci_get_by_type access_control wan_bp_ips)" -w "$(uci_get_by_type access_control wan_fw_ips)" \
+		-p "$(uci_get_by_type access_control lan_fp_ips)" -G "$(uci_get_by_type access_control lan_gm_ips)" -D "$proxyport" $mode $UDP $NF;do
+		[ $r -ge 20 ] && echo "`eval $DATE` SSR-rules : Start iptables rules failed!" >> $LOG && $BIN_DIR/ssr-rules -f && return 1
+		let r++;sleep 1
+	done
+	echo "`eval $DATE` SSR-rules : Start iptables rules successful!" >> $LOG
 }
 
 start_retcp(){
@@ -691,9 +691,9 @@ start_local(){
 	socks5_ip=$(uci_get_by_name $SO_SERVER server)
 	if ! echo $socks5_ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
 		if [ -f /var/lock/ssr-plusboot.lock ];then
-			retry=1
+			r=1
 			while ! nslookup $socks5_ip >/dev/null 2>&1;do
-				[ $retry -ge 20 ] && return 1 || let retry++
+				[ $r -ge 20 ] && return 1 || let r++
 				sleep 1
 			done
 		fi
